apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-stream
  labels:
    name: twitter-stream
spec:
  replicas: 1
  selector:
    matchLabels:
      name: twitter-stream
  template:
    metadata:
      labels:
        name: twitter-stream
    spec:
      containers:
      - name: twitter-to-pubsub
        image: gcr.io/google-samples/pubsub-bq-pipe:v5
        env:
        - name: PROCESSINGSCRIPT
          value: twitter-to-pubsub
        # Change this to your pubsub topic
        - name: twitter_final
          value: projects/test-twitter-305915/topics/twitter_final
        # Change the following four settings to your twitter credentials
        # information.
        - name: CONSUMERKEY
          value: KugVFdnHDFaah3oMY3fvfBwE
        - name: CONSUMERSECRET
          value: YNLZGXP0POGOSLOfjYT4NfdnYOW5sZ0BX3b7WaZK3cOentztfD
        - name: ACCESSTOKEN
          value: 1364162490398085120-rdJd69oKGCkV5DdDV2xYDkLMo5VDws
        - name: ACCESSTOKENSEC
          value: ita9cGBStyG1haVKPXxSWx36wNTdd7RyPSWKXhQUTHEVG
        - name: TWSTREAMMODE
          value: sample
